controller_list:
  - name: "ar2_arm/controllers/position" #"/ar3/controllers/position"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

