# ar3:
  joint_limits: # degrees
    joint_1:
      has_position_limits: true
      min_position: -2.96706 # -170.0
      max_position: 2.96706 # 170.0
      has_velocity_limits: true
      max_velocity: 1.57 # rad/s
      has_acceleration_limits: true
      max_acceleration: 1.57 # rad/s2
      has_jerk_limits: true
      max_jerk: 0.1
      has_effort_limits: false
      max_effort: 0.0
      min_effort: 0.0
    joint_2:
      has_position_limits: true
      min_position: -0.6911504 # -39.6
      max_position: 1.57079632679 # 90.0
      has_velocity_limits: true
      max_velocity: 1.57
      has_acceleration_limits: true
      max_acceleration: 1.57
      has_jerk_limits: true
      max_jerk: 0.1
      has_effort_limits: false
      max_effort: 0.0
      min_effort: 0.0
    joint_3:
      has_position_limits: true
      min_position: -1.745329 # -100.0
      max_position: 1.396263 # 80.0
      has_velocity_limits: true
      max_velocity: 1.57
      has_acceleration_limits: true
      max_acceleration: 1.57
      has_jerk_limits: true
      max_jerk: 0.1
      has_effort_limits: false
      max_effort: 0.0
      min_effort: 0.0
    joint_4:
      has_position_limits: true
      min_position: -1.22173 # -70.0
      max_position: 2.8710666 # 164.5
      has_velocity_limits: true
      max_velocity: 1.57
      has_acceleration_limits: true
      max_acceleration: 1.57
      has_jerk_limits: true
      max_jerk: 0.1
      has_effort_limits: false
      max_effort: 0.0
      min_effort: 0.0
    joint_5:
      has_position_limits: true
      min_position: -1.5707963 # -90.0
      max_position: 1.65806276 # 95.0
      has_velocity_limits: true
      max_velocity: 1.57
      has_acceleration_limits: true
      max_acceleration: 1.57
      has_jerk_limits: true
      max_jerk: 0.1
      has_effort_limits: false
      max_effort: 0.0
      min_effort: 0.0
    joint_6:
      has_position_limits: true
      min_position: -2.583087 # -148.0
      max_position: 2.583087 # 148.0
      has_velocity_limits: true
      max_velocity: 1.57
      has_acceleration_limits: true
      max_acceleration: 1.57
      has_jerk_limits: true
      max_jerk: 0.1
      has_effort_limits: false
      max_effort: 0.0
      min_effort: 0.0
