# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
#default_velocity_scaling_factor: 0.1
#default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits: # degrees
  joint_1:
    has_position_limits: true
    min_position: -2.96706 # -170.0
    max_position: 2.96706 # 170.0
    has_velocity_limits: true
    max_velocity: 2.36 # rad/s
    has_acceleration_limits: true
    max_acceleration: 1.57 # rad/s2
  joint_2:
    has_position_limits: true
    min_position: -0.6911504 # -39.6
    max_position: 1.57079632679 # 90.0
    has_velocity_limits: true
    max_velocity: 2.36
    has_acceleration_limits: true
    max_acceleration: 1.57
  joint_3:
    has_position_limits: true
    min_position: -1.745329 # -100.0
    max_position: 1.396263 # 80.0
    has_velocity_limits: true
    max_velocity: 2.36
    has_acceleration_limits: true
    max_acceleration: 1.57
  joint_4:
    has_position_limits: true
    min_position: -1.22173 # -70.0
    max_position: 2.8710666 # 164.5
    has_velocity_limits: true
    max_velocity: 2.36
    has_acceleration_limits: true
    max_acceleration: 1.57
  joint_5:
    has_position_limits: true
    min_position: -1.5707963 # -90.0
    max_position: 1.65806276 # 95.0
    has_velocity_limits: true
    max_velocity: 2.36
    has_acceleration_limits: true
    max_acceleration: 1.57
  joint_6:
    has_position_limits: true
    min_position: -2.583087 # -148.0
    max_position: 2.583087 # 148.0
    has_velocity_limits: true
    max_velocity: 2.36
    has_acceleration_limits: true
    max_acceleration: 1.57
